# Nixpacks configuration for Dokploy
[phases.setup]
command = "npm install"

[phases.build]
command = "npm run migrate:push && npm run build"

[phases.start]
command = "npm --prefix server install && npm --prefix server run build && npm --prefix server start & caddy run --config /assets/Caddyfile --adapter caddyfile"

[env]
NEON_DB_URL = "$NEON_DB_URL"
VITE_BACKEND_API_URL = "$VITE_BACKEND_API_URL"
ADMIN_PASSWORD = "$ADMIN_PASSWORD"
GEMINI_API_KEY = "$GEMINI_API_KEY"
API_KEY = "$API_KEY"