# Nixpacks configuration for Dokploy
[phases.setup]
command = "npm install"

[phases.build]
command = "npm run migrate:push && npm run build"

[phases.start]
command = "npm run preview -- --host 0.0.0.0 --port $PORT"

[env]
NEON_DB_URL = "$NEON_DB_URL"
ADMIN_PASSWORD = "$ADMIN_PASSWORD"
GEMINI_API_KEY = "$GEMINI_API_KEY"
API_KEY = "$API_KEY"